### PR TITLE
Risk Tracker v2.4 Release: Increase podmate budgets if everyone is vaccinated, fix bugs

### LINKED ISSUE #968: "indoors with air filter" option doesn't use industry standards; missing time element
[Issue brought up in email, dated June 2021, posted here at request of info@microcovid.org]

First, thanks for your contribution of the MicroCovid Tracker. I’ve used it (and loved it) for many months now.

I have a question about the Risk Tracker's version, v2.5, and the option within "Environment / Ventilation” dropdown, “indoors with a HEPA filter (flow rate of 5x room size).”

**Where is the element of time? Standard references to air flow involve a time element, such as "Air Changes Per Hour”** or the number of air changes in an hour that your air filter can perform given your square footage. New hospital construction typically aims for 12 air changes per hour. Source: Associated BodyWork and Massage Professionals’ monthly magazine, “How To Improve Treatment Room Air Quality: From Covid Protections to CO2 Concerns” by Julie Tudor. 

Caveat: Not all air in a room moves efficiently through an air filtration system, unless it’s forced air with vents spaced around the room to avoid slow moving spots. 

The way it’s written, I’ve got no way of knowing if I meet your criteria. 

Why this is important to me: I’m attempting to assess the risk for dropping my face mask mandate in my massage studio, to match new June 15 state guidelines. If I meet this HEPA filter standard, given all the safeguards I have in place, then it’s absolutely safe for me to allow clients to remove their face masks. If I don’t meet this criteria of “flow rate of 5x room size” then it’s absolutely NOT safe for me to allow clients to remove their face masks.

Obviously, I understand that these are ballpark estimates, and it’s only one part of my decision, but the micro covid tool has been so useful to me in the past - I’d love to be able to use it as one of my data points.

Thanks,
—A

### LINKED ISSUE #1012: Risk Tracker: Activity Risk should max out at partner level (60%) not housemate level (40%)
Need to update the risk tracker to max out at 60% instead of 40% so it matches the behavior of the calculator.

### LINKED ISSUE #1013: Risk Tracker: add option for "everyone in my house is vaccinated"
Following the formula we outlined here: https://www.microcovid.org/paper/all#2-if-a-vaccinated-individual-contracts-covid-how-much-less-or-more-likely-is-this-to-result-in-negative-consequences-increased-budget

### LINKED ISSUE #1033: Risk Tracker: bug in discounting environment influence on close proximity interactions
On the website, if you select 1 foot distance you get the following warning

> We are ignoring environment choice in this calculation. We are not confident that good ventilation or being outdoors substantially reduces the risk when people are this close to each other.

In the spreadsheet this appears to be handled by this fragment of the `Activity Log!F` formula

```
IF(AND(AD12=ACTIVITY_TITLE_CUDDLING,
             AA12=ACTIVITY_TITLE_OUTDOOR),
         ACTIVITY_TITLE_INDOOR,
         AA12)
```

But this special case doesn't apply to the other environments, such as planes, trains, "indoors with HEPA" or "a space with one or more sides open". This results in outdoor cuddling activities being rated 4x **more** dangerous than partially indoors, all other parameters the same.

### PR DESCRIPTION
**Pull request by blanchardjeremy**
- New: Reduce the budget reductions from other podmates if everyone in the pod is vaccinated since transmission is lower. Follows the formula [outlined here](https://www.microcovid.org/paper/13-q-and-a#2-if-a-vaccinated-individual-contracts-covid-how-much-less-or-more-likely-is-this-to-result-in-negative-consequences-increased-budget). Fixes #1013 
- New: Activity Risk now caps at the partner level (60%) instead of the housemate level (40%). Fixes #1012 
- Bugfix: Corrects the name of the HEPA filter location type to include "per hour" Fixes #968 
- Bugfix: Handles the case where we don't have vaccination data for a location, and the users selects "Avg local resident (vaccinated)" as the risk profile. #1037)
- Bugfix: Now correctly ignores "environment" when distance is set to "close" Fixes #1033

### CODE REVIEW

**Comment by blanchardjeremy** [comment]
I'm currently planning on going with Option #1 as outlined in #1013. Still open to input.

I'm adding this 2nd setting below the annual budget:

image


It includes this note upon hover:

This feature reduces the impact of other podmate's activities on each persons' budget, since transmission is lower between podmates now that you are all vaccinated. If some people in the pod are not vaccinated or received different types of vaccines, you have two main options. Let these two examples illustrate.

Example A: 5 podmates got Pfizer and 1 got J&J. The pod has a 1% annual risk budget. The person who got J&J doesn't mind being exposed to a bit more than 1% per year. So we set this setting to "Pfizer" because most people got Pfizer. This will overestimate the protection the J&J housemate has from other podmates, but the difference won't be drastic.

Example B: 5 podmates got Pfizer and 1 got J&J. The pod has a 1% annual risk budget. The person who got J&J definitely wants to stay under the 1% total budget. The pod, therefore, chooses "Johnson & Johnson" for this setting. Everyone doesn't get as much of an increase to their budget, but you all stay under the 1% annual budget.

Any suggestions to the wording?

**Comment by blanchardjeremy** [comment]
@beshaya ready for review.

**Comment by blanchardjeremy** [comment]
You can see the changelog entry here: https://deploy-preview-1017--microcov.netlify.app/tracker/changelog

**Comment by blanchardjeremy** [comment]
Final todo:

- [ ] Adjust the date of the release to match the actual final release.
- [ ] Send an update to Mailchimp listserv

**Comment by blanchardjeremy** [comment]
Final to do list:

- [ ] remove WIP from spreadsheet doc title
- [ ] Merge branch
- [ ] send a Mailchimp announcement

File: src/posts/tracker/changelog.ts [hunk 1]
```diff
@@ -15,6 +15,72 @@ interface Change {
...
 
 const changes: Change[] = [
+  {
+    date: new Date(2021, 7, 22),
+    versionNum: '2.4',
+    title: 'Increase podmate budgets if everyone is vaccinated',
+    spreadsheetURL:
+      'https://docs.google.com/spreadsheets/d/1Es4ZzLlNiBSxG5jJsGPUYewrCw2NqB5kDXlNfmdSdD0',
+    whatsNew: `
+* New: Low the budget reductions from other podmates if everyone in the pod is vaccinated since transmission is lower. Follows the [formula outlined here](/paper/13-q-and-a#2-if-a-vaccinated-individual-contracts-covid-how-much-less-or-more-likely-is-this-to-result-in-negative-consequences-increased-budget). ([#1013](https://github.com/microCOVID/microCOVID/issues/1013))
```
Comment (beshaya) [inline src/posts/tracker/changelog.ts:25]: "Low the budget reductions from other podmates"

I find the double negative to be confusing, would vaguely prefer "Increase individual budgets"

"transmission is lower" -> "transmission rate is lower" or "household transmission is less likely"

File: src/posts/tracker/changelog.ts [hunk 2]
```diff
@@ -15,6 +15,72 @@ interface Change {
...
+* New: Activity Risk now caps at the partner level (60%) instead of the housemate level (40%). ([#1012](https://github.com/microCOVID/microCOVID/issues/1012))
+* Bugfix: Handles the case where we don't have vaccination data for a location, and the users selects "Avg local resident (vaccinated)" as the risk profile. ([#1037](https://github.com/microCOVID/microCOVID/issues/1037))
+* Bugfix: Corrects the name of the *HEPA filter* location type to include "per hour". ([#968](https://github.com/microCOVID/microCOVID/issues/968))
+* Bugfix: Now correctly ignores "environment" when distance is set to "close" ([#1033](https://github.com/microCOVID/microCOVID/issues/1033))
+
+**Note on how the vaccination budget adjustment works:** This feature reduces the impact of other podmate's activities on each persons' budget, since transmission is lower between podmates now that you are all vaccinated. If some people in the pod are not vaccinated or received different types of vaccines, you have two main options. Let these two examples illustrate.
```
Comment (beshaya) [inline src/posts/tracker/changelog.ts:31]: "transmission is less likely" or "transmission rate is lower"

"you have two main options" -> "we provide two options:"
"Let these two examples illustrate." remove?

File: src/posts/tracker/changelog.ts [hunk 3]
```diff
@@ -15,6 +15,72 @@ interface Change {
...
+  * **Example A:** 5 podmates got Pfizer and 1 got J&J. The pod has a 1% annual risk budget. The person who got J&J doesn't mind being exposed to a bit more than 1% per year. So we set this setting to "Pfizer" because most people got Pfizer. This will overestimate the protection the J&J housemate has from other podmates, but the difference won't be drastic.
```
Comment (beshaya) [inline src/posts/tracker/changelog.ts:32]: "This will overestimate the protection the J&J housemate has from other podmates" -> This will set individual budgets that, if completely used, will put the housemate with J&J at above 1% risk of getting COVID. In this particular scenario, the podmate with the J&J vaccine may be exposed to up to a X% chance of getting COVID per year."

**Review by beshaya — APPROVED** [review]
Left some suggestions, otherwise LGTM.

File: src/posts/tracker/changelog.ts (hunk 1 above)
Comment (blanchardjeremy) [reply src/posts/tracker/changelog.ts:25]: done

File: src/posts/tracker/changelog.ts (hunk 3 above)
Comment (blanchardjeremy) [reply src/posts/tracker/changelog.ts:32]: Done
