### PR TITLE
Remove all references to the Intermediate Method

### LINKED ISSUE #746: Person Risk Page links to removed intermediate method
Page: https://www.microcovid.org/paper/6-person-risk
Broken link is in this sentence, IIRC the intermediate method has been removed entirely "The Intermediate Method adds adjustments for whether the person is or isn’t an essential worker."

PS Sorry to make so many issues in a row instead of batching them together, I didn't think I'd come across more than one

### PR DESCRIPTION
**Pull request by blanchardjeremy**
Closes #746

### CODE REVIEW

File: src/posts/paper/13-q-and-a.ts [hunk 1]
```diff
@@ -292,7 +292,7 @@ In terms of qualitative scales, we like the following:
...
 [^unwell]: You probably can't do this anywhere near as reliably with someone you don't live with, which is why the discussion here is specific to housemates.
 [^2]: This is due to the fact that much less transmission occurs more than 3 days before the appearance of symptoms ([He et al](https://www.nature.com/articles/s41591-020-0869-5), figure 1c middle graph) or fewer than 2 days after infection ([Ferretti et al](https://science.sciencemag.org/content/368/6491/eabb6936), figure 1 “generation time”). In order for Carol to infect Bob before Alice shows symptoms, Carol’s generation time would have to be greater than the delay between Alice’s infectiousness and Alice’s symptoms, which is unlikely.
-[^3]: When we do these calculations, the lowest Person Risk we allow ourselves to assign anyone is 1/100th the Intermediate Person Risk, just as a safety margin.
+[^3]: When we do these calculations, the lowest Person Risk we allow ourselves to assign anyone is 1/100th the risk of an average person in your area, just as a safety margin.
```
Comment (beshaya) [inline src/posts/paper/13-q-and-a.ts:295]: Should we change this to 1/200? I don't think it makes particularly much sense to raise it, since it is, after all, arbitrary.

**Review by beshaya — COMMENTED** [review]
Thanks for taking care of this!

I think this will cause a merge conflict with the vaccines writeup, I would like to land that first, if that seems ok with you.

**Comment by blanchardjeremy** [comment]
Fine by me!

**Review by beshaya — APPROVED** [review]
